# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest: 
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    view:
#        view_response_listener:  true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, jpeg ] }
            - { path: ^/publicapi, prefer_extension: true, fallback_format: json, priorities: [ json, jpeg ] }
            - { path: ^/, prefer_extension: false, fallback_format: html, priorities: [ html ] }

    param_fetcher_listener: true
